# Generated by Django 3.1.2 on 2020-11-12 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackList',
            fields=[
                ('BackNo', models.AutoField(primary_key=True, serialize=False)),
                ('BackPic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('BookNo', models.AutoField(primary_key=True, serialize=False)),
                ('BookTitle', models.CharField(max_length=30)),
                ('typeCnt', models.IntegerField(null=True)),
                ('wordCnt', models.IntegerField(null=True)),
                ('CreateDateTime', models.DateTimeField()),
                ('ModifyDateTime', models.DateTimeField(null=True)),
                ('UserNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharList',
            fields=[
                ('CharNo', models.AutoField(primary_key=True, serialize=False)),
                ('CharPic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WordType',
            fields=[
                ('typeEnum', models.IntegerField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('WordNo', models.AutoField(primary_key=True, serialize=False)),
                ('WordContext', models.CharField(max_length=10)),
                ('WordType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_Publisher.wordtype')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birth', models.IntegerField(null=True)),
                ('RegisterDateTime', models.DateTimeField()),
                ('UserNo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookTextList',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('Page', models.IntegerField()),
                ('Text', models.CharField(max_length=200)),
                ('BookNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_Publisher.bookinfo')),
            ],
        ),
        migrations.CreateModel(
            name='BookContetnsList',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('Page', models.IntegerField()),
                ('X', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('Y', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('Scale', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('Rotation', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('Reversed', models.BooleanField(default=False)),
                ('BookNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_Publisher.bookinfo')),
                ('CharNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AI_Publisher.charlist')),
            ],
        ),
        migrations.CreateModel(
            name='BookBackList',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('Page', models.IntegerField()),
                ('BackNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AI_Publisher.backlist')),
                ('BookNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_Publisher.bookinfo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bookbacklist',
            constraint=models.UniqueConstraint(fields=('BookNo', 'Page'), name='unique'),
        ),
    ]
