# Generated by Django 3.1.2 on 2020-11-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_Publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=200)),
                ('imgUrl', models.CharField(max_length=200)),
                ('width', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('top', models.CharField(max_length=200)),
                ('left', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='BookTitle',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='CreateDateTime',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='UserNo',
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundUrl', models.CharField(max_length=200)),
                ('context', models.CharField(max_length=200)),
                ('elements', models.ManyToManyField(to='AI_Publisher.BookElement')),
            ],
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='bookPages',
            field=models.ManyToManyField(to='AI_Publisher.BookPage'),
        ),
    ]
